[build]
  command = "pnpm run build"
  publish = "dist"
  base = "frontend"

[build.environment]
  NODE_VERSION = "18"

# Configure secrets scanning
[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.images]
  compress = true

# Configure secrets scanning
[build.processing.secrets]
  enabled = true
  omit_keys = ["VITE_API_URL"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 