[build]
  command = "rm -rf dist && pnpm run build:prod"
  publish = "dist"
  base = "frontend"

[build.environment]
  NODE_VERSION = "18"

# Configure build processing
[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.images]
  compress = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 